module.exports = ({
	de:{
		MSG_HELLO: 'Hallo', // MSG_HELLO olacak şekilde değiştirelim
		MSG_HBDAY : "Herzlichen Glueckwunsch",
		MSG_LOGIN : "Einloggen",
		MSG_LOGOUT:"Abmelden",
		MSG_REGISTER : "Anmelden",
		MSG_SHOOTAPOST : "Beitrag Senden",
		MSG_POSTSSHOT : "Post geschickt",
		MSG_YOUAREPOSTINGAS : "Schick beitrag als ",
		MSG_SUBMIT : "Einreichen",
		MSG_CLOSE:"Schließen",
		MSG_SHIT :"Scheisse!",
		MSG_USERNAME:"Benutzername",
		MSG_PASSWORD:"Passwort",
		MSG_TOPIC:"Titel",
		MSG_ENTRY:"Text",
		MSG_BACK:"Zurück",
		MSG_POSTS:"Beiträge",
		MSG_BAN:"Verbote",
		MSG_DEL:"Löschen",
		MSG_SEARCH:"Suchen",
		MSG_TURKISH:"Türkisch",
		MSG_ENGLISH:"Englisch",
		MSG_GERMAN:"Deutsch",
		MSG_LANGUAGE:"Sprachen",
		MSG_FOOTERTEXT:"Dieses Projekt wurde im Markafoni erstellt und wird als interne Sharing-Plattform unter den IT-Team verwendet werden"
	},
	en:{
		MSG_HELLO: 'Hello',
		MSG_HBDAY : "Happy Birthday",
		MSG_LOGIN : "Login",
		MSG_LOGOUT:"Logout",
		MSG_REGISTER : "Register",
		MSG_SHOOTAPOST : "Shoot-a-post!",
		MSG_POSTSSHOT : "Posts-shot",
		MSG_YOUAREPOSTINGAS : "You are posting as ",
		MSG_SUBMIT : "Submit",
		MSG_CLOSE:"Close",
		MSG_SHIT :"Shit happened :(",
		MSG_USERNAME:"Username",
		MSG_PASSWORD:"Password",
		MSG_TOPIC:"Title",
		MSG_ENTRY:"Text",
		MSG_BACK:"Back",
		MSG_POSTS:"Posts",
		MSG_BAN:"Ban",
		MSG_DEL:"Delete",
		MSG_SEARCH:"Search",
		MSG_TURKISH:"Turkish",
		MSG_ENGLISH:"English",
		MSG_GERMAN:"German",
		MSG_LANGUAGE:"Languages",
		MSG_FOOTERTEXT:"this project was created in markafoni & will be used as an internal sharing platform among the IT team"
	},
	tr:{
		MSG_HELLO: 'Merhaba',
		MSG_HBDAY : "Doğumgünün kutlu olsun",
		MSG_LOGIN : "Giriş yap",
		MSG_LOGOUT:"Çıkış yap",
		MSG_REGISTER : "Kayıt ol",
		MSG_SHOOTAPOST : "Yazı gönder",
		MSG_POSTSSHOT : "Gönderilen yazılar",
		MSG_YOUAREPOSTINGAS : "Yazıyı şu kişi olarak göndereceksiniz: ",
		MSG_SUBMIT : "Gönder",
		MSG_CLOSE:"Kapat",
		MSG_SHIT :"Olur böyle şeyler :(",
		MSG_USERNAME:"Kullanıcı adı",
		MSG_PASSWORD:"Şifre",
		MSG_TOPIC:"Başlık",
		MSG_ENTRY:"Yazı",
		MSG_BACK:"Geri",
		MSG_POSTS:"Yazılar",
		MSG_BAN:"Yasakla",
		MSG_DEL:"Sil",
		MSG_SEARCH:"Ara",
		MSG_TURKISH:"Türkçe",
		MSG_ENGLISH:"İngilizce",
		MSG_GERMAN:"Almanca",
		MSG_LANGUAGE:"Diller",
		MSG_FOOTERTEXT:"Bu proje markafoni bünyesinde IT takımının aralarında paylaşım yapmaları amacıyla yaratılmıştır"
	}
});