module.exports = ({
	de:{
		hello: 'Hallo',
		hbday : "Herzlichen Glueckwunsch",
		login : "Einloggen",
		logout:"Abmelden",
		register : "Anmelden",
		shootAPost : "Beitrag Senden",
		postsShot : "Post geschickt",
		youArePostingAs : "Schick beitrag als ",
		submit : "Einreichen",
		close:"Schließen",
		shit :"Scheisse!",
		username:"Benutzername",
		password:"Passwort",
		topic:"Titel",
		entry:"Text",
		back:"Zurück",
		posts:"Beiträge",
		ban:"Verbote",
		del:"Löschen",
		search:"Suchen",
		turkish:"Türkisch",
		english:"Englisch",
		german:"Deutsch",
		language:"Sprachen",
		footerText:"Dieses Projekt wurde im Markafoni erstellt und wird als interne Sharing-Plattform unter den IT-Team verwendet werden"
	},
	en:{
		hello: 'Hello',
		hbday : "Happy Birthday",
		login : "Login",
		logout:"Logout",
		register : "Register",
		shootAPost : "Shoot-a-post!",
		postsShot : "Posts-shot",
		youArePostingAs : "You are posting as ",
		submit : "Submit",
		close:"Close",
		shit :"Shit happened :(",
		username:"Username",
		password:"Password",
		topic:"Title",
		entry:"Text",
		back:"Back",
		posts:"Posts",
		ban:"Ban",
		del:"Delete",
		search:"Search",
		turkish:"Turkish",
		english:"English",
		german:"German",
		language:"Languages",
		footerText:"this project was created in markafoni & will be used as an internal sharing platform among the IT team"
	},
	tr:{
		hello: 'Merhaba',
		hbday : "Doğumgünün kutlu olsun",
		login : "Giriş yap",
		logout:"Çıkış yap",
		register : "Kayıt ol",
		shootAPost : "Yazı gönder",
		postsShot : "Gönderilen yazılar",
		youArePostingAs : "Yazıyı şu kişi olarak göndereceksiniz: ",
		submit : "Gönder",
		close:"Kapat",
		shit :"Olur böyle şeyler :(",
		username:"Kullanıcı adı",
		password:"Şifre",
		topic:"Başlık",
		entry:"Yazı",
		back:"Geri",
		posts:"Yazılar",
		ban:"Yasakla",
		del:"Sil",
		search:"Ara",
		turkish:"Türkçe",
		english:"İngilizce",
		german:"Almanca",
		language:"Diller",
		footerText:"Bu proje markafoni bünyesinde IT takımının aralarında paylaşım yapmaları amacıyla yaratılmıştır"
	}
});