module.exports = ({
	de:{
		hello: 'Hallo',
		hbday : "Herzlichen Glueckwunsch",
		login : "Einloggen",
		register : "Anmelden",
		shootAPost : "Beitrag Senden",
		postsShot : "Post geschickt",
		youArePostingAs : "Schick beitrag als ",
		submit : "Einreichen",
		close:"Schließen",
		shit :"Scheisse!",
		username:"Benutzername",
		password:"Passwort",
		topic:"Titel",
		entry:"Text",
		back:"Zurück",
		posts:"Beiträge"
	},
	en:{
		hello: 'Hello',
		hbday : "Happy Birthday",
		login : "Login",
		register : "Register",
		shootAPost : "Shoot-a-post!",
		postsShot : "Posts-shot",
		youArePostingAs : "You are posting as ",
		submit : "Submit",
		close:"Close",
		shit :"Shit happened :(",
		username:"Username",
		password:"Password",
		topic:"Title",
		entry:"Text",
		back:"Back",
		posts:"Posts"
	},
	tr:{
		hello: 'Merhaba',
		hbday : "Doğumgünün kutlu olsun",
		login : "Giriş yap",
		register : "Kayıt ol",
		shootAPost : "Yazı gönder",
		postsShot : "Gönderilen yazılar",
		youArePostingAs : "Yazıyı şu kişi olarak göndereceksiniz: ",
		submit : "Gönder",
		close:"Kapat",
		shit :"Olur böyle şeyler :(",
		username:"Kullanıcı adı",
		password:"Şifre",
		topic:"Başlık",
		entry:"Yazı",
		back:"Geri",
		posts:"Yazılar"
	}
});